// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplateauth = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/connector-factories": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接器"
                ],
                "summary": "连接器工厂列表",
                "parameters": [
                    {
                        "type": "string",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "provider",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoconnector.ConnectorFactoryListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/connectors": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接器"
                ],
                "summary": "连接器列表分页",
                "parameters": [
                    {
                        "type": "string",
                        "description": "显示名称",
                        "name": "displayName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 1000,
                        "type": "integer",
                        "description": "每页数据条数",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "协议类型",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "提供商",
                        "name": "provider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "租户ID",
                        "name": "tenantID",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoauth.ConnectorPageListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接器"
                ],
                "summary": "创建连接器",
                "parameters": [
                    {
                        "description": "创建连接器",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtoauth.ConnectorCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoauth.ConnectorCreateResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/connectors/callback": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接器"
                ],
                "summary": "连接器回调",
                "parameters": [
                    {
                        "type": "string",
                        "description": "连接器ID",
                        "name": "connectorID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "授权码",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoauth.LoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/connectors/{connectorID}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接器"
                ],
                "summary": "连接器详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "连接器ID",
                        "name": "connectorID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoauth.ConnectorDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接器"
                ],
                "summary": "修改连接器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "连接器ID",
                        "name": "connectorID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改连接器",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtoauth.ConnectorUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接器"
                ],
                "summary": "删除连接器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "连接器ID",
                        "name": "connectorID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/connectors/{connectorID}/authorize": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接器"
                ],
                "summary": "连接器授权",
                "parameters": [
                    {
                        "type": "string",
                        "description": "连接器ID",
                        "name": "connectorID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "连接器授权",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtoconnector.ConnectorAuthorizeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoconnector.ConnectorAuthorizeResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/connectors/{connectorID}/test": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接器"
                ],
                "summary": "测试连接器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "连接器ID",
                        "name": "connectorID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoconnector.ConnectorTestResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/joinTenant": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "加入租户",
                "parameters": [
                    {
                        "description": "加入租户",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtoauth.JoinTenantReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoauth.JoinTenantResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登出（全局：撤销全部 refresh token + SSO 会话）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/me": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "自然人管理"
                ],
                "summary": "获取自然人详情",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoperson.PersonDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/me/changePassword": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "自然人管理"
                ],
                "summary": "更新自然人密码",
                "parameters": [
                    {
                        "description": "更新自然人密码",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtoperson.PersonUpdatePasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/me/sessions": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话管理"
                ],
                "summary": "会话列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 1000,
                        "type": "integer",
                        "description": "每页数据条数",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtouser.SessionListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话管理"
                ],
                "summary": "撤销所有会话",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/me/sessions/{sessionID}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话管理"
                ],
                "summary": "撤销会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话记录ID（会话列表中的 id 字段，即 refresh token 记录主键）",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/me/tenants": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "我的租户列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoauth.MyTenantsResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/auth/userinfo": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoauth.UserinfoResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtoauth.ConnectorCreateReq": {
            "type": "object",
            "properties": {
                "allowAccountLink": {
                    "description": "是否允许账号关联",
                    "type": "boolean"
                },
                "allowAutoCreateUser": {
                    "description": "是否允许自动创建用户",
                    "type": "boolean"
                },
                "claimMapping": {
                    "description": "声明映射"
                },
                "config": {
                    "description": "连接器配置"
                },
                "displayName": {
                    "description": "显示名称",
                    "type": "string"
                },
                "domainPolicy": {
                    "description": "域策略"
                },
                "enableTokenStorage": {
                    "description": "是否启用令牌存储",
                    "type": "boolean"
                },
                "name": {
                    "description": "连接器名称",
                    "type": "string"
                },
                "protocol": {
                    "description": "协议类型",
                    "type": "string"
                },
                "provider": {
                    "description": "提供商",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "syncProfile": {
                    "description": "是否同步资料",
                    "type": "boolean"
                },
                "tenantID": {
                    "description": "租户ID",
                    "type": "string"
                }
            }
        },
        "dtoauth.ConnectorCreateResp": {
            "type": "object",
            "properties": {
                "connectorID": {
                    "description": "连接器ID",
                    "type": "string"
                }
            }
        },
        "dtoauth.ConnectorDetailResp": {
            "type": "object",
            "properties": {
                "allowAccountLink": {
                    "description": "是否允许账号关联",
                    "type": "boolean"
                },
                "allowAutoCreateUser": {
                    "description": "是否允许自动创建用户",
                    "type": "boolean"
                },
                "claimMapping": {
                    "description": "声明映射"
                },
                "config": {
                    "description": "连接器配置"
                },
                "connectorID": {
                    "description": "连接器ID",
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "创建人id",
                    "type": "integer"
                },
                "displayName": {
                    "description": "显示名称",
                    "type": "string"
                },
                "domainPolicy": {
                    "description": "域策略"
                },
                "enableTokenStorage": {
                    "description": "是否启用令牌存储",
                    "type": "boolean"
                },
                "name": {
                    "description": "连接器名称",
                    "type": "string"
                },
                "protocol": {
                    "description": "协议类型",
                    "type": "string"
                },
                "provider": {
                    "description": "提供商",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "syncProfile": {
                    "description": "是否同步资料",
                    "type": "boolean"
                },
                "tenantID": {
                    "description": "租户ID",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "更新人id",
                    "type": "integer"
                }
            }
        },
        "dtoauth.ConnectorPageListItem": {
            "type": "object",
            "properties": {
                "allowAccountLink": {
                    "description": "是否允许账号关联",
                    "type": "boolean"
                },
                "allowAutoCreateUser": {
                    "description": "是否允许自动创建用户",
                    "type": "boolean"
                },
                "claimMapping": {
                    "description": "声明映射"
                },
                "config": {
                    "description": "连接器配置"
                },
                "connectorID": {
                    "description": "连接器ID",
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "创建人id",
                    "type": "integer"
                },
                "displayName": {
                    "description": "显示名称",
                    "type": "string"
                },
                "domainPolicy": {
                    "description": "域策略"
                },
                "enableTokenStorage": {
                    "description": "是否启用令牌存储",
                    "type": "boolean"
                },
                "name": {
                    "description": "连接器名称",
                    "type": "string"
                },
                "protocol": {
                    "description": "协议类型",
                    "type": "string"
                },
                "provider": {
                    "description": "提供商",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "syncProfile": {
                    "description": "是否同步资料",
                    "type": "boolean"
                },
                "tenantID": {
                    "description": "租户ID",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "更新人id",
                    "type": "integer"
                }
            }
        },
        "dtoauth.ConnectorPageListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "数据列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtoauth.ConnectorPageListItem"
                    }
                },
                "total": {
                    "description": "数据总条数",
                    "type": "integer"
                }
            }
        },
        "dtoauth.ConnectorUpdateReq": {
            "type": "object",
            "properties": {
                "allowAccountLink": {
                    "description": "是否允许账号关联",
                    "type": "boolean"
                },
                "allowAutoCreateUser": {
                    "description": "是否允许自动创建用户",
                    "type": "boolean"
                },
                "claimMapping": {
                    "description": "声明映射"
                },
                "config": {
                    "description": "连接器配置"
                },
                "displayName": {
                    "description": "显示名称",
                    "type": "string"
                },
                "domainPolicy": {
                    "description": "域策略"
                },
                "enableTokenStorage": {
                    "description": "是否启用令牌存储",
                    "type": "boolean"
                },
                "name": {
                    "description": "连接器名称",
                    "type": "string"
                },
                "protocol": {
                    "description": "协议类型",
                    "type": "string"
                },
                "provider": {
                    "description": "提供商",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "syncProfile": {
                    "description": "是否同步资料",
                    "type": "boolean"
                },
                "tenantID": {
                    "description": "租户ID",
                    "type": "string"
                }
            }
        },
        "dtoauth.JoinTenantReq": {
            "type": "object",
            "properties": {
                "inviteCode": {
                    "description": "邀请码（主门禁）",
                    "type": "string"
                }
            }
        },
        "dtoauth.JoinTenantResp": {
            "type": "object",
            "properties": {
                "userID": {
                    "description": "用户ID",
                    "type": "string"
                }
            }
        },
        "dtoauth.LoginResp": {
            "type": "object",
            "properties": {
                "ssoSessionID": {
                    "type": "string"
                },
                "tenants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/objauth.TenantOption"
                    }
                }
            }
        },
        "dtoauth.MyTenantsResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/objauth.TenantOption"
                    }
                }
            }
        },
        "dtoauth.UserinfoResp": {
            "type": "object",
            "properties": {
                "personInfo": {
                    "$ref": "#/definitions/objauth.PersonInfo"
                },
                "userInfo": {
                    "$ref": "#/definitions/objauth.TenantUserInfo"
                }
            }
        },
        "dtoconnector.ConnectorAuthorizeReq": {
            "type": "object",
            "required": [
                "redirectUri"
            ],
            "properties": {
                "loginHint": {
                    "type": "string"
                },
                "redirectUri": {
                    "type": "string"
                },
                "responseMode": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "dtoconnector.ConnectorAuthorizeResp": {
            "type": "object",
            "properties": {
                "authorizationUrl": {
                    "type": "string"
                }
            }
        },
        "dtoconnector.ConnectorFactoryListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtoconnector.ConnectorFactoryResp"
                    }
                }
            }
        },
        "dtoconnector.ConnectorFactoryResp": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "configSchema": {},
                "defaultScopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "displayName": {
                    "type": "string"
                },
                "factoryID": {
                    "type": "string"
                },
                "isStandard": {
                    "type": "boolean"
                },
                "protocol": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "dtoconnector.ConnectorTestResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dtoperson.PersonDetailResp": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "isSuspended": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "personID": {
                    "type": "string"
                },
                "primaryEmail": {
                    "type": "string"
                },
                "primaryPhone": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dtoperson.PersonUpdatePasswordReq": {
            "type": "object",
            "required": [
                "newPassword",
                "oldPassword"
            ],
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "oldPassword": {
                    "type": "string"
                }
            }
        },
        "dtouser.SessionListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtouser.SessionResp"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dtouser.SessionResp": {
            "type": "object",
            "properties": {
                "appID": {
                    "type": "string"
                },
                "clientIP": {
                    "type": "string"
                },
                "clientType": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间(unix 秒)",
                    "type": "integer"
                },
                "expiresAt": {
                    "description": "过期时间(unix 秒)",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "sessionID": {
                    "type": "string"
                },
                "tenantID": {
                    "type": "string"
                },
                "userAgent": {
                    "type": "string"
                }
            }
        },
        "gincontext.DtoRender": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                },
                "requestID": {
                    "type": "string"
                }
            }
        },
        "objauth.PersonInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "personID": {
                    "description": "自然人ID",
                    "type": "string"
                }
            }
        },
        "objauth.TenantOption": {
            "type": "object",
            "properties": {
                "isOwner": {
                    "description": "是否租户拥有者",
                    "type": "boolean"
                },
                "name": {
                    "description": "租户名称",
                    "type": "string"
                },
                "tag": {
                    "description": "租户标识",
                    "type": "string"
                },
                "tenantID": {
                    "description": "租户ID",
                    "type": "string"
                },
                "userID": {
                    "description": "用户ID",
                    "type": "string"
                }
            }
        },
        "objauth.TenantUserInfo": {
            "type": "object",
            "properties": {
                "isOwner": {
                    "description": "是否租户拥有者",
                    "type": "boolean"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "tenantID": {
                    "description": "租户ID",
                    "type": "string"
                },
                "userID": {
                    "description": "用户ID",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfoauth holds exported Swagger Info so clients can modify it
var SwaggerInfoauth = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "auth",
	SwaggerTemplate:  docTemplateauth,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoauth.InstanceName(), SwaggerInfoauth)
}
