// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplateiam = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/iam/tenant/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "创建租户管理",
                "parameters": [
                    {
                        "description": "创建租户管理",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtotenant.TenantCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"requestID\": \"xxx\", \"data\": \"ok\", \"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtotenant.TenantCreateResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/iam/tenant/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "删除租户管理",
                "parameters": [
                    {
                        "description": "删除租户管理",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtotenant.TenantDeleteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"requestID\": \"xxx\", \"data\": \"ok\", \"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/iam/tenant/detail": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "租户管理详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "租户ID",
                        "name": "tenantID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"requestID\": \"xxx\", \"data\": \"ok\", \"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtotenant.TenantDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/iam/tenant/pageList": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "租户管理列表分页",
                "parameters": [
                    {
                        "description": "租户管理列表",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtotenant.TenantPageListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"requestID\": \"xxx\", \"data\": \"ok\", \"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtotenant.TenantPageListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/iam/tenant/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "修改租户管理",
                "parameters": [
                    {
                        "description": "修改租户管理",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtotenant.TenantUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"requestID\": \"xxx\", \"data\": \"ok\", \"msg\": \"修改成功\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtotenant.TenantCreateReq": {
            "type": "object",
            "properties": {
                "dbUser": {
                    "description": "数据库用户",
                    "type": "string"
                },
                "isSuspended": {
                    "description": "是否挂起",
                    "type": "integer"
                },
                "name": {
                    "description": "租户名称",
                    "type": "string"
                },
                "tag": {
                    "description": "标签",
                    "type": "string"
                }
            }
        },
        "dtotenant.TenantCreateResp": {
            "type": "object",
            "properties": {
                "tenantID": {
                    "description": "租户ID",
                    "type": "integer"
                }
            }
        },
        "dtotenant.TenantDeleteReq": {
            "type": "object",
            "required": [
                "tenantID"
            ],
            "properties": {
                "tenantID": {
                    "description": "租户ID",
                    "type": "integer"
                }
            }
        },
        "dtotenant.TenantDetailResp": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "创建人id",
                    "type": "integer"
                },
                "dbUser": {
                    "description": "数据库用户",
                    "type": "string"
                },
                "isSuspended": {
                    "description": "是否挂起",
                    "type": "integer"
                },
                "name": {
                    "description": "租户名称",
                    "type": "string"
                },
                "tag": {
                    "description": "标签",
                    "type": "string"
                },
                "tenantID": {
                    "description": "租户ID",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "更新人id",
                    "type": "integer"
                }
            }
        },
        "dtotenant.TenantPageListItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "创建人id",
                    "type": "integer"
                },
                "dbUser": {
                    "description": "数据库用户",
                    "type": "string"
                },
                "isSuspended": {
                    "description": "是否挂起",
                    "type": "integer"
                },
                "name": {
                    "description": "租户名称",
                    "type": "string"
                },
                "tag": {
                    "description": "标签",
                    "type": "string"
                },
                "tenantID": {
                    "description": "租户ID",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "更新人id",
                    "type": "integer"
                }
            }
        },
        "dtotenant.TenantPageListReq": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页数据条数",
                    "type": "integer",
                    "maximum": 1000
                }
            }
        },
        "dtotenant.TenantPageListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "数据列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtotenant.TenantPageListItem"
                    }
                },
                "total": {
                    "description": "数据总条数",
                    "type": "integer"
                }
            }
        },
        "dtotenant.TenantUpdateReq": {
            "type": "object",
            "required": [
                "tenantID"
            ],
            "properties": {
                "dbUser": {
                    "description": "数据库用户",
                    "type": "string"
                },
                "isSuspended": {
                    "description": "是否挂起",
                    "type": "integer"
                },
                "name": {
                    "description": "租户名称",
                    "type": "string"
                },
                "tag": {
                    "description": "标签",
                    "type": "string"
                },
                "tenantID": {
                    "description": "租户ID",
                    "type": "integer"
                }
            }
        },
        "gincontext.DtoRender": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                },
                "requestID": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfoiam holds exported Swagger Info so clients can modify it
var SwaggerInfoiam = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "iam",
	SwaggerTemplate:  docTemplateiam,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoiam.InstanceName(), SwaggerInfoiam)
}
